# Generated by Django 5.1.7 on 2025-03-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
