# Generated by Django 5.1.7 on 2025-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_additives_tags_product_allergens_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
