# Generated by Django 5.1.7 on 2025-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_brand_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ecoscore_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
