# Generated by Django 5.1.7 on 2025-04-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_ingredients_product_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
