# Generated by Django 5.1.7 on 2025-04-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
