# Generated by Django 5.1.7 on 2025-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_productviewlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="imported_categories",
            field=models.ManyToManyField(
                blank=True, related_name="imported_products", to="api.category"
            ),
        ),
    ]
